
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-02-13T13:57:46+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "60e6f861527e28aa3611c56da31ae05fdddf2fcf",
 "version": "v0.5.0"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
