# This file is automatically generated, DO NOT EDIT
# fmt: off

from os.path import abspath, join, dirname, exists
_root = abspath(dirname(__file__))

# runtime dependencies
import wpiutil._init_wpiutil
import hal._init_wpiHal
import _pyntcore._init_ntcore
import wpimath._impl._init_wpimath_cpp
from ctypes import cdll

try:
    _lib = cdll.LoadLibrary(join(_root, "lib", "libhalsim_gui.dylib"))
except FileNotFoundError:
    if not exists(join(_root, "lib", "libhalsim_gui.dylib")):
        raise FileNotFoundError("libhalsim_gui.dylib was not found on your system. Is this package correctly installed?")
    raise FileNotFoundError("libhalsim_gui.dylib could not be loaded. There is a missing dependency.")

