
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-02-10T15:24:08+0100",
 "dirty": false,
 "error": null,
 "full-revisionid": "acada8ce439c5682d63ee52272211f0a9ee46a9f",
 "version": "0.2.2"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
