
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-02-05T10:09:47-0500",
 "dirty": false,
 "error": null,
 "full-revisionid": "6ae0df42b7abdf28b315af00fd344b12174dde53",
 "version": "1.3"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
