# -*- coding: utf-8 -*-
# Generated by Django 1.11.27 on 2020-02-02 15:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangoldp_event', '0002_auto_20200202_1639'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='img',
            field=models.URLField(blank=True, null=True, verbose_name="Illustration de l'évènement"),
        ),
    ]
