
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-02-05T12:27:18+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "72acfb6548dddb31af10584dff3028d803bb2e68",
 "version": "4.16"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
