# Generated by Django 2.2.11 on 2020-06-19 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('remo', '0007_delete_duplicated_tags'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserVersion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('version', models.CharField(max_length=20, null=True)),
                ('client_ip', models.CharField(max_length=100, null=True)),
            ],
            options={
                'db_table': 'user_versions',
            },
        ),
    ]
