# Generated by Django 2.2.11 on 2020-06-22 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('remo', '0008_userversion'),
    ]

    operations = [
        migrations.AddField(
            model_name='annotationsetstatistics',
            name='done_images',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='annotationsetstatistics',
            name='todo_images',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='annotationsetstatistics',
            name='total_images_without_annotations',
            field=models.IntegerField(default=0),
        ),
    ]
