# Generated by Django 2.2.11 on 2020-07-09 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('remo', '0012_auto_20200707_1251'),
    ]

    operations = [
        migrations.AddField(
            model_name='agrinstallations',
            name='client_ip',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='agrstats',
            name='client_ip',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='agrusage',
            name='client_ip',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
