# Generated by Django 2.2.11 on 2020-09-23 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('remo', '0017_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdetails',
            name='allow_marketing_emails',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userdetails',
            name='company',
            field=models.TextField(blank=True, null=True),
        ),
    ]
