# Generated by Django 2.2.11 on 2021-02-05 21:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('remo', '0022_datasetsettings'),
        ('remo', '0022_usersessions'),
    ]

    operations = [
    ]
