
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-02-11T04:31:30+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "bf1e571708a792d218eb6b4474a287f4fc7a31bf",
 "version": "1.14.6.post.dev97"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
