
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-02-10T07:49:03+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "06144fc60104d09b1c92e48a7dff2b591aa5affd",
 "version": "0.6.2.post.dev182"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
