
 

// This file is autogenerated. DO NOT EDIT

#pragma once
#include <robotpy_build.h>


#include <frc/buttons/JoystickButton.h>

#include <frc/smartdashboard/SendableBuilder.h>
#include <frc/buttons/Trigger.h>
#include <frc/commands/Command.h>
#include <frc/commands/CommandGroup.h>




#include <rpygen/frc__Button.hpp>

namespace rpygen {

using namespace frc;


template <typename PyTrampolineBase, typename CxxBase = PyTrampolineBase>
using PyBasefrc__JoystickButton = 
    Pyfrc__Button<
        PyTrampolineBase
    
    , CxxBase
    >
;

template <typename PyTrampolineBase, typename CxxBase = PyTrampolineBase>
struct Pyfrc__JoystickButton : PyBasefrc__JoystickButton<PyTrampolineBase, CxxBase> {
    using PyBasefrc__JoystickButton<PyTrampolineBase, CxxBase>::PyBasefrc__JoystickButton;



#ifndef RPYGEN_DISABLE_Get_v
    bool Get() override {
PYBIND11_OVERRIDE_NAME(PYBIND11_TYPE(bool), CxxBase, "get", Get,);    }
#endif




};

}; // namespace rpygen
