from datalib.datasets import CustomData
from datalib.keras_datasets import Mnist
from datalib.keras_datasets import FashionMnist
from datalib.keras_datasets import Cifar10
from datalib.keras_datasets import Cifar100
from datalib.sklearn_datasets import BreastCancer
from datalib.sklearn_datasets import Hepatitis
from datalib.sklearn_datasets import Iris
from datalib.sklearn_datasets import Lfw
from datalib.sklearn_datasets import Wine
from datalib.downloaded_datasets import TinyImagenet