#!/usr/bin/env python
# -*- coding: utf8 -*-

BOOLEAN = ('bool')
CODE = ('code')
STRING = ('str')
UNICODE = ('unicode')
BYTES = ('bytes')
STRINGS = ('str', 'unicode', 'bytes')
INTEGER = ('int')
FLOAT = ('float')
LONG = ('long')
DECIMAL = ('Decimal')
NUMBERS = ('int', 'float', 'Decimal', 'long')
LIST = ('list')
SET = ('set')
TUPLE = ('tuple')
GENERATOR = ('generator')
ITERABLES = ('list', 'set', 'tuple', 'generator')
DICTIONARY = ('dict')
NONE = ('NoneType')
TYPE = ('type')
FILE = ('file')
