# coding: utf-8

"""
    Foxtail Trainer

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: v1
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest
import datetime

import foxtail_trainer_api
from foxtail_trainer_api.models.worker_ml_model_dto import WorkerMLModelDto  # noqa: E501
from foxtail_trainer_api.rest import ApiException

class TestWorkerMLModelDto(unittest.TestCase):
    """WorkerMLModelDto unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional):
        """Test WorkerMLModelDto
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # model = foxtail_trainer_api.models.worker_ml_model_dto.WorkerMLModelDto()  # noqa: E501
        if include_optional :
            return WorkerMLModelDto(
                id = '0', 
                name = '0', 
                model_type = 'Xgboost', 
                data_set_url = '0', 
                status = 'Created', 
                download_url = '0', 
                training_result_id = '0'
            )
        else :
            return WorkerMLModelDto(
        )

    def testWorkerMLModelDto(self):
        """Test WorkerMLModelDto"""
        inst_req_only = self.make_instance(include_optional=False)
        inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == '__main__':
    unittest.main()
