# coding: utf-8

"""
    Foxtail Trainer

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: v1
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest
import datetime

import foxtail_trainer_api
from foxtail_trainer_api.models.deleted_ml_models_dto import DeletedMLModelsDto  # noqa: E501
from foxtail_trainer_api.rest import ApiException

class TestDeletedMLModelsDto(unittest.TestCase):
    """DeletedMLModelsDto unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional):
        """Test DeletedMLModelsDto
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # model = foxtail_trainer_api.models.deleted_ml_models_dto.DeletedMLModelsDto()  # noqa: E501
        if include_optional :
            return DeletedMLModelsDto(
                deleted_ml_models_count = 56, 
                rejected_to_delete_ml_models = [
                    '0'
                    ]
            )
        else :
            return DeletedMLModelsDto(
        )

    def testDeletedMLModelsDto(self):
        """Test DeletedMLModelsDto"""
        inst_req_only = self.make_instance(include_optional=False)
        inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == '__main__':
    unittest.main()
