# coding: utf-8

"""
    Foxtail Trainer

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: v1
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import foxtail_trainer_api
from foxtail_trainer_api.api.ml_model_api import MLModelApi  # noqa: E501
from foxtail_trainer_api.rest import ApiException


class TestMLModelApi(unittest.TestCase):
    """MLModelApi unit test stubs"""

    def setUp(self):
        self.api = foxtail_trainer_api.api.ml_model_api.MLModelApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_api_job_job_id_ml_model_add_post(self):
        """Test case for api_job_job_id_ml_model_add_post

        Add ML models to the job  # noqa: E501
        """
        pass

    def test_api_job_job_id_ml_model_delete_all_delete(self):
        """Test case for api_job_job_id_ml_model_delete_all_delete

        Delete ML models from job  # noqa: E501
        """
        pass

    def test_api_job_job_id_ml_model_get_all_get(self):
        """Test case for api_job_job_id_ml_model_get_all_get

        Get list of model guids for job  # noqa: E501
        """
        pass

    def test_api_job_job_id_ml_model_get_id_get(self):
        """Test case for api_job_job_id_ml_model_get_id_get

        """
        pass

    def test_api_job_job_id_ml_model_update_ml_models_put(self):
        """Test case for api_job_job_id_ml_model_update_ml_models_put

        """
        pass

    def test_api_job_job_id_ml_model_update_status_id_put(self):
        """Test case for api_job_job_id_ml_model_update_status_id_put

        """
        pass


if __name__ == '__main__':
    unittest.main()
