# coding: utf-8

"""
    Foxtail Trainer

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: v1
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import foxtail_trainer_api
from foxtail_trainer_api.api.report_api import ReportApi  # noqa: E501
from foxtail_trainer_api.rest import ApiException


class TestReportApi(unittest.TestCase):
    """ReportApi unit test stubs"""

    def setUp(self):
        self.api = foxtail_trainer_api.api.report_api.ReportApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_api_job_job_id_report_get_job_metric_get(self):
        """Test case for api_job_job_id_report_get_job_metric_get

        """
        pass

    def test_api_job_job_id_report_get_ml_models_metric_get(self):
        """Test case for api_job_job_id_report_get_ml_models_metric_get

        """
        pass

    def test_api_job_job_id_report_get_ml_models_status_counts_get(self):
        """Test case for api_job_job_id_report_get_ml_models_status_counts_get

        """
        pass

    def test_api_job_job_id_report_get_ml_models_status_get(self):
        """Test case for api_job_job_id_report_get_ml_models_status_get

        Get status for every model. Report contains model id and current status.  # noqa: E501
        """
        pass

    def test_api_job_job_id_report_get_ml_models_url_get(self):
        """Test case for api_job_job_id_report_get_ml_models_url_get

        """
        pass

    def test_api_job_job_id_report_get_training_time_get(self):
        """Test case for api_job_job_id_report_get_training_time_get

        """
        pass


if __name__ == '__main__':
    unittest.main()
