# coding: utf-8

"""
    Foxtail Trainer

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: v1
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest
import datetime

import foxtail_trainer_api
from foxtail_trainer_api.models.ml_models_status_list_report_dto import MLModelsStatusListReportDto  # noqa: E501
from foxtail_trainer_api.rest import ApiException

class TestMLModelsStatusListReportDto(unittest.TestCase):
    """MLModelsStatusListReportDto unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional):
        """Test MLModelsStatusListReportDto
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # model = foxtail_trainer_api.models.ml_models_status_list_report_dto.MLModelsStatusListReportDto()  # noqa: E501
        if include_optional :
            return MLModelsStatusListReportDto(
                count = 56, 
                ml_models_statuses = [
                    foxtail_trainer_api.models.ml_models_status_report_dto.MLModelsStatusReportDto(
                        model_id = '0', 
                        model_status = 'Created', )
                    ]
            )
        else :
            return MLModelsStatusListReportDto(
        )

    def testMLModelsStatusListReportDto(self):
        """Test MLModelsStatusListReportDto"""
        inst_req_only = self.make_instance(include_optional=False)
        inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == '__main__':
    unittest.main()
