
# This file was generated by 'versioneer.py' (0.17) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-02-05T13:39:20-0600",
 "dirty": false,
 "error": null,
 "full-revisionid": "cbb88bd43288a7e25a03e11f17e1c9a2f5e6f31d",
 "version": "2021.02.0"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
