
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-02-11T04:59:08-0500",
 "dirty": false,
 "error": null,
 "full-revisionid": "9940debdea0d671bb51cba6e8c95f25ef0c35ce0",
 "version": "0.0.1"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
