
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-02-10T08:19:54-0800",
 "dirty": false,
 "error": null,
 "full-revisionid": "039c5e4e0bfc171f26516c37cb5f80f315ea1c40",
 "version": "4.3.5"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
