
 

// This file is autogenerated. DO NOT EDIT

#pragma once
#include <robotpy_build.h>


#include <frc/commands/ConditionalCommand.h>

#include <frc/smartdashboard/SendableBuilder.h>
#include <frc/commands/Command.h>
#include <frc/commands/CommandGroup.h>




#include <rpygen/frc__Command.hpp>

namespace rpygen {

using namespace frc;


template <typename PyTrampolineBase, typename CxxBase = PyTrampolineBase>
using PyBasefrc__ConditionalCommand = 
    Pyfrc__Command<
        PyTrampolineBase
    
    , CxxBase
    >
;

template <typename PyTrampolineBase, typename CxxBase = PyTrampolineBase>
struct Pyfrc__ConditionalCommand : PyBasefrc__ConditionalCommand<PyTrampolineBase, CxxBase> {
    using PyBasefrc__ConditionalCommand<PyTrampolineBase, CxxBase>::PyBasefrc__ConditionalCommand;



#ifndef RPYGEN_DISABLE_Condition_v
    bool Condition() override {
RPYBUILD_OVERRIDE_PURE_NAME(ConditionalCommand,PYBIND11_TYPE(bool), CxxBase, "_condition", Condition,);    }
#endif

#ifndef RPYGEN_DISABLE__Initialize_v
    void _Initialize() override {
PYBIND11_OVERRIDE_NAME(PYBIND11_TYPE(void), CxxBase, "_initialize", _Initialize,);    }
#endif

#ifndef RPYGEN_DISABLE__Cancel_v
    void _Cancel() override {
PYBIND11_OVERRIDE_NAME(PYBIND11_TYPE(void), CxxBase, "_cancel", _Cancel,);    }
#endif

#ifndef RPYGEN_DISABLE_IsFinished_v
    bool IsFinished() override {
PYBIND11_OVERRIDE_NAME(PYBIND11_TYPE(bool), CxxBase, "isFinished", IsFinished,);    }
#endif

#ifndef RPYGEN_DISABLE__Interrupted_v
    void _Interrupted() override {
PYBIND11_OVERRIDE_NAME(PYBIND11_TYPE(void), CxxBase, "_interrupted", _Interrupted,);    }
#endif




};

}; // namespace rpygen
