
 

// This file is autogenerated. DO NOT EDIT

#pragma once
#include <robotpy_build.h>


#include <../../build/temp.linux-x86_64-3.6/dlstatic/ctre_api/include/ctre/phoenix/motorcontrol/IFollower.h>

#include <ctre/phoenix/motorcontrol/IMotorController.h>





namespace rpygen {

using namespace ctre::phoenix::motorcontrol;


template <typename PyTrampolineBase, typename CxxBase = PyTrampolineBase>
struct Pyctre__phoenix__motorcontrol__IFollower : PyTrampolineBase {
    using PyTrampolineBase::PyTrampolineBase;



#ifndef RPYGEN_DISABLE_Follow_RTIMotorController
    void Follow(ctre::phoenix::motorcontrol::IMotorController& masterToFollow) override {
RPYBUILD_OVERRIDE_PURE_NAME(IFollower,PYBIND11_TYPE(void), CxxBase, "follow", Follow,masterToFollow);    }
#endif

#ifndef RPYGEN_DISABLE_ValueUpdated_v
    void ValueUpdated() override {
RPYBUILD_OVERRIDE_PURE_NAME(IFollower,PYBIND11_TYPE(void), CxxBase, "valueUpdated", ValueUpdated,);    }
#endif




};

}; // namespace rpygen
