
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-02-07T14:07:04+0100",
 "dirty": false,
 "error": null,
 "full-revisionid": "11cd0c80a19a7f794f6a87f56870d3164e727f16",
 "version": "0.12a3"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
