import os

AEROSPIKE_EVIDENCE_URL = os.getenv('AEROSPIKE_EVIDENCE_URL')
AEROSPIKE_EVIDENCE_TTL = os.getenv('AEROSPIKE_EVIDENCE_TTL', 2592000)
AEROSPIKE_EVIDENCE_TIMEOUT = os.getenv('AEROSPIKE_EVIDENCE_TIMEOUT', 0.800)

SPLUNK_URL = os.getenv('SPLUNK_URL')
SPLUNK_LOG_FORMAT = os.getenv('SPLUNK_LOG_FORMAT')
SPLUNK_LOG_HANDLER_NAME = os.getenv('SPLUNK_LOG_HANDLER_NAME', 'Log')
