# -*- coding: utf-8 -*-

from sofacomponents.lib.base_component import sofa_component


"""
Component SimpleTesselatedTetraMechanicalMapping

.. autofunction:: SimpleTesselatedTetraMechanicalMapping

Indices and tables
******************

* :ref:`genindex`
* :ref:`modindex`
* :ref:`search`
"""


@sofa_component
def SimpleTesselatedTetraMechanicalMapping(self, **kwargs):
    """
    Mechanical mapping between two TetrahedronSetTopologies generated by SimpleTesselatedTetraTopologicalMapping



    """
    params = dict()
    return "SimpleTesselatedTetraMechanicalMapping", params
