from ExtractC.main import *
from ExtractC.config import *
from ExtractC.ocr import *
from ExtractC.processing import *
from ExtractC.ctpn_model import *
from ExtractC.classify import *
from ExtractC.ctpn_utils import *
from ExtractC.ctpn_predict import *
from ExtractC.idCard_class import *
from ExtractC.studentCard_class import *
from ExtractC.drivingLicense_class import *
