
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-02-08T22:50:53+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "ed0d5b72c431a9106915a7ff9ee83e459990a82b",
 "version": "4.16.1"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
