from .datasets import CustomData
from .keras_datasets import Mnist
from .keras_datasets import FashionMnist
from .keras_datasets import Cifar10
from .keras_datasets import Cifar100
from .sklearn_datasets import BreastCancer
from .sklearn_datasets import Hepatitis
from .sklearn_datasets import Iris
from .sklearn_datasets import Lfw
from .sklearn_datasets import Wine