# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-08-12 14:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangoldp_event', '0008_merge_20200812_1009'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='img',
            field=models.URLField(default='http://localhost:8000/media/defaultevent.png', verbose_name="Illustration de l'évènement"),
        ),
    ]
