# -*- coding: utf-8 -*-
# Generated by Django 1.11.27 on 2020-02-02 15:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangoldp_event', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='facebook',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Lien Facebook'),
        ),
        migrations.AlterField(
            model_name='event',
            name='link',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Lien internet'),
        ),
    ]
