# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-08-12 09:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('djangoldp_event', '0006_auto_20200709_1411'),
        ('djangoldp_event', '0004_auto_20200426_1603'),
    ]

    operations = [
    ]
