# Generated by Django 2.2.16 on 2020-09-23 10:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('djangoldp_event', '0010_auto_20200812_1459'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='circle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to='djangoldp_circle.Circle'),
        ),
        migrations.AlterField(
            model_name='event',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='djangoldp_event.Locationevent', verbose_name="Lieu de l'évènement"),
        ),
    ]
