# coding: utf-8

"""
    REST API

    Rockset's REST API allows for creating and managing all resources in Rockset. Each supported endpoint is documented below.  All requests must be authorized with a Rockset API key, which can be created in the [Rockset console](https://console.rockset.com). The API key must be provided as `ApiKey <api_key>` in the `Authorization` request header. For example: ``` Authorization: ApiKey aB35kDjg93J5nsf4GjwMeErAVd832F7ad4vhsW1S02kfZiab42sTsfW5Sxt25asT ```  All endpoints are only accessible via https.  Build something awesome!  # noqa: E501

    OpenAPI spec version: v1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six

from rockset.swagger_client.models.aws_access_key import AwsAccessKey  # noqa: F401,E501
from rockset.swagger_client.models.aws_role import AwsRole  # noqa: F401,E501


class KinesisIntegration(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'aws_access_key': 'AwsAccessKey',
        'aws_role': 'AwsRole'
    }

    attribute_map = {
        'aws_access_key': 'aws_access_key',
        'aws_role': 'aws_role'
    }

    def __init__(self, **kwargs):  # noqa: E501
        """KinesisIntegration - a model defined in Swagger"""  # noqa: E501

        self._aws_access_key = None
        self._aws_role = None
        self.discriminator = None

        self.aws_access_key = kwargs.pop('aws_access_key', None)
        self.aws_role = kwargs.pop('aws_role', None)

    @property
    def aws_access_key(self):
        """Gets the aws_access_key of this KinesisIntegration.  # noqa: E501

        credentials for an AWS access key integration  # noqa: E501

        :return: The aws_access_key of this KinesisIntegration.  # noqa: E501
        :rtype: AwsAccessKey
        """
        return self._aws_access_key

    @aws_access_key.setter
    def aws_access_key(self, aws_access_key):
        """Sets the aws_access_key of this KinesisIntegration.

        credentials for an AWS access key integration  # noqa: E501

        :param aws_access_key: The aws_access_key of this KinesisIntegration.  # noqa: E501
        :type: AwsAccessKey
        """

        self._aws_access_key = aws_access_key

    @property
    def aws_role(self):
        """Gets the aws_role of this KinesisIntegration.  # noqa: E501

        details of an AWS cross-account role integration  # noqa: E501

        :return: The aws_role of this KinesisIntegration.  # noqa: E501
        :rtype: AwsRole
        """
        return self._aws_role

    @aws_role.setter
    def aws_role(self, aws_role):
        """Sets the aws_role of this KinesisIntegration.

        details of an AWS cross-account role integration  # noqa: E501

        :param aws_role: The aws_role of this KinesisIntegration.  # noqa: E501
        :type: AwsRole
        """

        self._aws_role = aws_role

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(KinesisIntegration, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, KinesisIntegration):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other

    def __getitem__(self, item):
        return getattr(self, item)

    def get(self, item):
        return getattr(self, item)

    def items(self):
        return self.to_dict().items()

    def __setitem__(self, item, value):
        return seattr(self, item, value)
