
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-02-12T21:36:22+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "5335e49bfd5a904e8ea6d6254d205c1f5a990c5f",
 "version": "0.8.261"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
