
 

// This file is autogenerated. DO NOT EDIT

#pragma once
#include <robotpy_build.h>


#include <frc/buttons/ReleasedButtonScheduler.h>

#include <frc/smartdashboard/SendableBuilder.h>
#include <frc/buttons/Trigger.h>
#include <frc/commands/Command.h>
#include <frc/commands/CommandGroup.h>




#include <rpygen/frc__ButtonScheduler.hpp>

namespace rpygen {

using namespace frc;


template <typename PyTrampolineBase, typename CxxBase = PyTrampolineBase>
using PyBasefrc__ReleasedButtonScheduler = 
    Pyfrc__ButtonScheduler<
        PyTrampolineBase
    
    , CxxBase
    >
;

template <typename PyTrampolineBase, typename CxxBase = PyTrampolineBase>
struct Pyfrc__ReleasedButtonScheduler : PyBasefrc__ReleasedButtonScheduler<PyTrampolineBase, CxxBase> {
    using PyBasefrc__ReleasedButtonScheduler<PyTrampolineBase, CxxBase>::PyBasefrc__ReleasedButtonScheduler;



#ifndef RPYGEN_DISABLE_Execute_v
    void Execute() override {
PYBIND11_OVERRIDE_NAME(PYBIND11_TYPE(void), CxxBase, "execute", Execute,);    }
#endif




};

}; // namespace rpygen
