
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-02-11T23:05:30+1100",
 "dirty": false,
 "error": null,
 "full-revisionid": "acb4516a82488941d81ebbb4d3cb30c9e1b39fcf",
 "version": "0.4.0"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
