
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-02-10T13:14:45+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "2402d013bd5bbb39b472fefca926b8f064dbb102",
 "version": "1.14.6.post.dev95"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
