# coding: utf-8

"""
    Aliro Quantum App

    This is an api for the Aliro Quantum App  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Contact: nick@aliroquantum.com
    Generated by: https://openapi-generator.tech
"""


import pprint
import re  # noqa: F401

import six

from aliro_quantum.configuration import Configuration


class ChangePasswordParameters(object):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    """
    Attributes:
      openapi_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    openapi_types = {
        'user_email': 'str',
        'old_password': 'str',
        'new_password': 'str'
    }

    attribute_map = {
        'user_email': 'userEmail',
        'old_password': 'oldPassword',
        'new_password': 'newPassword'
    }

    def __init__(self, user_email=None, old_password=None, new_password=None, local_vars_configuration=None):  # noqa: E501
        """ChangePasswordParameters - a model defined in OpenAPI"""  # noqa: E501
        if local_vars_configuration is None:
            local_vars_configuration = Configuration()
        self.local_vars_configuration = local_vars_configuration

        self._user_email = None
        self._old_password = None
        self._new_password = None
        self.discriminator = None

        if user_email is not None:
            self.user_email = user_email
        if old_password is not None:
            self.old_password = old_password
        if new_password is not None:
            self.new_password = new_password

    @property
    def user_email(self):
        """Gets the user_email of this ChangePasswordParameters.  # noqa: E501


        :return: The user_email of this ChangePasswordParameters.  # noqa: E501
        :rtype: str
        """
        return self._user_email

    @user_email.setter
    def user_email(self, user_email):
        """Sets the user_email of this ChangePasswordParameters.


        :param user_email: The user_email of this ChangePasswordParameters.  # noqa: E501
        :type: str
        """

        self._user_email = user_email

    @property
    def old_password(self):
        """Gets the old_password of this ChangePasswordParameters.  # noqa: E501


        :return: The old_password of this ChangePasswordParameters.  # noqa: E501
        :rtype: str
        """
        return self._old_password

    @old_password.setter
    def old_password(self, old_password):
        """Sets the old_password of this ChangePasswordParameters.


        :param old_password: The old_password of this ChangePasswordParameters.  # noqa: E501
        :type: str
        """

        self._old_password = old_password

    @property
    def new_password(self):
        """Gets the new_password of this ChangePasswordParameters.  # noqa: E501


        :return: The new_password of this ChangePasswordParameters.  # noqa: E501
        :rtype: str
        """
        return self._new_password

    @new_password.setter
    def new_password(self, new_password):
        """Sets the new_password of this ChangePasswordParameters.


        :param new_password: The new_password of this ChangePasswordParameters.  # noqa: E501
        :type: str
        """

        self._new_password = new_password

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.openapi_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, ChangePasswordParameters):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, ChangePasswordParameters):
            return True

        return self.to_dict() != other.to_dict()
