# coding: utf-8

"""
    Aliro Quantum App

    This is an api for the Aliro Quantum App  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Contact: nick@aliroquantum.com
    Generated by: https://openapi-generator.tech
"""


import pprint
import re  # noqa: F401

import six

from aliro_quantum.configuration import Configuration


class ExecutionParameters(object):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    """
    Attributes:
      openapi_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    openapi_types = {
        'num_shots': 'int',
        'output_type': 'str'
    }

    attribute_map = {
        'num_shots': 'numShots',
        'output_type': 'outputType'
    }

    def __init__(self, num_shots=None, output_type=None, local_vars_configuration=None):  # noqa: E501
        """ExecutionParameters - a model defined in OpenAPI"""  # noqa: E501
        if local_vars_configuration is None:
            local_vars_configuration = Configuration()
        self.local_vars_configuration = local_vars_configuration

        self._num_shots = None
        self._output_type = None
        self.discriminator = None

        self.num_shots = num_shots
        if output_type is not None:
            self.output_type = output_type

    @property
    def num_shots(self):
        """Gets the num_shots of this ExecutionParameters.  # noqa: E501


        :return: The num_shots of this ExecutionParameters.  # noqa: E501
        :rtype: int
        """
        return self._num_shots

    @num_shots.setter
    def num_shots(self, num_shots):
        """Sets the num_shots of this ExecutionParameters.


        :param num_shots: The num_shots of this ExecutionParameters.  # noqa: E501
        :type: int
        """
        if self.local_vars_configuration.client_side_validation and num_shots is None:  # noqa: E501
            raise ValueError("Invalid value for `num_shots`, must not be `None`")  # noqa: E501

        self._num_shots = num_shots

    @property
    def output_type(self):
        """Gets the output_type of this ExecutionParameters.  # noqa: E501

        [real, simulated, both]   # noqa: E501

        :return: The output_type of this ExecutionParameters.  # noqa: E501
        :rtype: str
        """
        return self._output_type

    @output_type.setter
    def output_type(self, output_type):
        """Sets the output_type of this ExecutionParameters.

        [real, simulated, both]   # noqa: E501

        :param output_type: The output_type of this ExecutionParameters.  # noqa: E501
        :type: str
        """

        self._output_type = output_type

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.openapi_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, ExecutionParameters):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, ExecutionParameters):
            return True

        return self.to_dict() != other.to_dict()
