
#
# ENCRYPTION KEY
#
ENCRYPTION_KEY_ENV_NAME = 'SZCZYPIOREK_ENCRYPTION_KEY'

ENCRYPTION_KEY_FILE_ENV_NAME = 'SZCZYPIOREK_ENCRYPTION_KEY_FILE'

ENCRYPTION_KEY_DEFAULT = '.szczypiorek_encryption_key'

#
# ENVRIONMENT
#
ENVIRONMENT_ENV_NAME = 'SZCZYPIOREK_ENVIRONMENT'

ENVIRONMENT_FILE_ENV_NAME = 'SZCZYPIOREK_ENVIRONMENT_FILE'

ENVIRONMENT_DEFAULT = 'env.szczyp'

#
# SETTINGS
#
ENCRYPTION_KEY_LENGTH = 128
