
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-02-10T10:36:15-0800",
 "dirty": false,
 "error": null,
 "full-revisionid": "9141ad93996a769d2eb3d49176a0b0ab9ade3c67",
 "version": "v1.5.0"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
