
 

// This file is autogenerated. DO NOT EDIT

#pragma once
#include <robotpy_build.h>


#include <frc/commands/PrintCommand.h>

#include <frc/smartdashboard/SendableBuilder.h>
#include <frc/commands/Command.h>
#include <frc/commands/CommandGroup.h>




#include <rpygen/frc__InstantCommand.hpp>

namespace rpygen {

using namespace frc;


template <typename PyTrampolineBase, typename CxxBase = PyTrampolineBase>
using PyBasefrc__PrintCommand = 
    Pyfrc__InstantCommand<
        PyTrampolineBase
    
    , CxxBase
    >
;

template <typename PyTrampolineBase, typename CxxBase = PyTrampolineBase>
struct Pyfrc__PrintCommand : PyBasefrc__PrintCommand<PyTrampolineBase, CxxBase> {
    using PyBasefrc__PrintCommand<PyTrampolineBase, CxxBase>::PyBasefrc__PrintCommand;



#ifndef RPYGEN_DISABLE_Initialize_v
    void Initialize() override {
PYBIND11_OVERRIDE_NAME(PYBIND11_TYPE(void), CxxBase, "initialize", Initialize,);    }
#endif




};

}; // namespace rpygen
