DEVIATION = "protocol_deviation"
PROTOCOL_DEVIATION_VIOLATION_ACTION = "submit-protocol-deviation-violation"
UNBLINDING_REQUEST_ACTION = "unblinding-request"
UNBLINDING_REVIEW_ACTION = "unblinding-review"
VIOLATION = "protocol_violation"
MEDICATION_NONCOMPLIANCE = "medication_noncompliance"
