
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-02-09T14:53:25+0100",
 "dirty": false,
 "error": null,
 "full-revisionid": "3a144d2ffcf09d1abc999c4a8e0b0a1fc3719a08",
 "version": "3.0.2"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
