# coding: utf-8

"""
    MimePost API Reference (Beta)

    MimePost API for sending email.  You can find out more about MimePost at [https://mimepost.com](http://mimepost.com). For this sample, you can use the api key `special-key` to test the authorization     filters.  # noqa: E501

    OpenAPI spec version: 0.1.0
    Contact: support@mimepost.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import MimePost
from MimePost.models.account_profile_response import AccountProfileResponse  # noqa: E501
from MimePost.rest import ApiException


class TestAccountProfileResponse(unittest.TestCase):
    """AccountProfileResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testAccountProfileResponse(self):
        """Test AccountProfileResponse"""
        # FIXME: construct object with mandatory attributes with example values
        # model = MimePost.models.account_profile_response.AccountProfileResponse()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
