
# This file was generated by 'versioneer.py' (0.15) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json
import sys

version_json = '''
{
 "dirty": false,
 "error": null,
 "full-revisionid": "85dc54883c53b5ee721ecffc60d79d535e3bf02d",
 "version": "2402"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
