
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-02-09T07:11:17-0600",
 "dirty": false,
 "error": null,
 "full-revisionid": "00ca1775a9ae7bc9b7894872ea9b394c4fe7133e",
 "version": "v0.6.1"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
