# Generated by Django 2.2.11 on 2020-05-01 14:44
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('remo', '0005_delete_duplicated_objects'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='annotationobject',
            unique_together={('annotation', 'name')},
        ),
    ]
