# Generated by Django 2.2.11 on 2020-08-18 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('remo', '0015_rename_datasets'),
    ]

    operations = [
        migrations.AddField(
            model_name='agrinstallations',
            name='cloud_platform',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
