# Generated by Django 2.2.11 on 2021-01-29 19:05

from django.db import migrations, models
import django.db.models.deletion
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('remo', '0021_auto_20201120_1420'),
    ]

    operations = [
        migrations.CreateModel(
            name='DatasetSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('settings', jsonfield.fields.JSONField(null=True)),
                ('dataset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dataset_settings', to='remo.Dataset')),
            ],
            options={
                'db_table': 'dataset_settings',
            },
        ),
    ]
