from enum import Enum


class DispatchMode(Enum):
    ASYNC = "async"
    SYNC = "sync"


# Debug Logger Names
NARRATION_RECORD_PREFIX = "narration-record-"
NARRATION_HANDLER_PREFIX = "narration-handler-"
NARRATION_DEBUG_LOG_PREFIX = "narration._debug"
NARRATION_DEBUG_HANDLER_PREFIX = f"{NARRATION_DEBUG_LOG_PREFIX}._handler"
NARRATION_DEBUG_HANDLER_NATIVE_PREFIX = f"{NARRATION_DEBUG_HANDLER_PREFIX}.native"
NARRATION_DEBUG_HANDLER_ZMQ_PREFIX = f"{NARRATION_DEBUG_HANDLER_PREFIX}.zmq"
NARRATION_DEBUG_HANDLER_THREAD_PREFIX = f"{NARRATION_DEBUG_HANDLER_PREFIX}.thread"
NARRATION_DEBUG_HANDLER_THREAD_ZMQ_PREFIX = f"{NARRATION_DEBUG_HANDLER_THREAD_PREFIX}.zmq"
NARRATION_DEBUG_HANDLER_THREAD_NATIVE_PREFIX = f"{NARRATION_DEBUG_HANDLER_THREAD_PREFIX}.native"
NARRATION_DEBUG_HANDLER_SOCKET_PREFIX = f"{NARRATION_DEBUG_LOG_PREFIX}.socket"
NARRATION_DEBUG_HANDLER_SOCKET_ZMQ_PREFIX = f"{NARRATION_DEBUG_HANDLER_SOCKET_PREFIX}.zmq"
NARRATION_DEBUG_HANDLER_SOCKET_NATIVE_PREFIX = f"{NARRATION_DEBUG_HANDLER_SOCKET_PREFIX}.native"
