
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-02-08T14:23:55+0100",
 "dirty": false,
 "error": null,
 "full-revisionid": "0afe4a18e771c81dba51c6175de94f7d9da3b390",
 "version": "0.1.0"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
