
 

// This file is autogenerated. DO NOT EDIT

#pragma once
#include <robotpy_build.h>


#include <AHRS.h>




#define RPYGEN_DISABLE_InitSendable_RTSendableBuilder

#include <rpygen/frc__SendableBase.hpp>
#include <rpygen/frc__ErrorBase.hpp>
#include <rpygen/frc__PIDSource.hpp>
#include <rpygen/frc__Gyro.hpp>

namespace rpygen {



template <typename PyTrampolineBase, typename CxxBase = PyTrampolineBase>
using PyBase__AHRS = 
    Pyfrc__SendableBase<
    Pyfrc__ErrorBase<
    Pyfrc__PIDSource<
    Pyfrc__Gyro<
        PyTrampolineBase
    
    , CxxBase
    >
    
    , CxxBase
    >
    
    , CxxBase
    >
    
    , CxxBase
    >
;

template <typename PyTrampolineBase, typename CxxBase = PyTrampolineBase>
struct Py__AHRS : PyBase__AHRS<PyTrampolineBase, CxxBase> {
    using PyBase__AHRS<PyTrampolineBase, CxxBase>::PyBase__AHRS;



#ifndef RPYGEN_DISABLE_KGetAngle_v
    double GetAngle() const override {
PYBIND11_OVERRIDE_NAME(PYBIND11_TYPE(double), CxxBase, "getAngle", GetAngle,);    }
#endif

#ifndef RPYGEN_DISABLE_KGetRate_v
    double GetRate() const override {
PYBIND11_OVERRIDE_NAME(PYBIND11_TYPE(double), CxxBase, "getRate", GetRate,);    }
#endif

#ifndef RPYGEN_DISABLE_Reset_v
    void Reset() override {
PYBIND11_OVERRIDE_NAME(PYBIND11_TYPE(void), CxxBase, "reset", Reset,);    }
#endif

#ifndef RPYGEN_DISABLE_Calibrate_v
    void Calibrate() override {
PYBIND11_OVERRIDE_NAME(PYBIND11_TYPE(void), CxxBase, "calibrate", Calibrate,);    }
#endif




};

}; // namespace rpygen
