
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-02-11T14:59:23-0600",
 "dirty": false,
 "error": null,
 "full-revisionid": "3312602c567038e6430b9680075431ab3814b199",
 "version": "0.9.22"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
