# Generated by Django 3.0.7 on 2021-02-10 23:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('django_occupations', '0004_add_name_to_sochighlevel'),
    ]

    operations = [
        migrations.AddField(
            model_name='onetalternatetitle',
            name='soc_occupations',
            field=models.ManyToManyField(related_name='onet_alternate_titles', to='django_occupations.SOCDetailedOccupation'),
        ),
        migrations.AlterField(
            model_name='onetalternatetitle',
            name='soc_occupation',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='onet_alternate_title', to='django_occupations.SOCDetailedOccupation'),
        ),
    ]
