
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-02-13T14:12:59-0500",
 "dirty": false,
 "error": null,
 "full-revisionid": "a81076efbfa7f299f147b6bd8595d1d5ef4a9e37",
 "version": "0.0.8"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
