
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-02-11T12:34:10+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "74f4eb6f8e2644dbc475e41ba28fc08f1aa325d5",
 "version": "0.2.9"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
