# This file is automatically generated, DO NOT EDIT
# fmt: off

from os.path import abspath, join, dirname, exists
_root = abspath(dirname(__file__))

# runtime dependencies
import wpilib._impl._init_wpilibc
import wpiutil._init_wpiutil
import _pyntcore._init_ntcore
import wpilib._init_wpilib
from ctypes import cdll

try:
    _lib = cdll.LoadLibrary(join(_root, "lib", "libwpilibOldCommands.dylib"))
except FileNotFoundError:
    if not exists(join(_root, "lib", "libwpilibOldCommands.dylib")):
        raise FileNotFoundError("libwpilibOldCommands.dylib was not found on your system. Is this package correctly installed?")
    raise FileNotFoundError("libwpilibOldCommands.dylib could not be loaded. There is a missing dependency.")

