
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-02-11T16:29:05+0100",
 "dirty": false,
 "error": null,
 "full-revisionid": "716a2bf4a39f31b0d1d3723eb0b5616694f00a6f",
 "version": "0.2.4"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
