# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'rectangleSelection.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_rectangleSelection(object):
    def setupUi(self, rectangleSelection):
        rectangleSelection.setObjectName("rectangleSelection")
        rectangleSelection.resize(575, 275)
        rectangleSelection.setMinimumSize(QtCore.QSize(575, 275))
        self.gridLayout_2 = QtWidgets.QGridLayout(rectangleSelection)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.updateButton = QtWidgets.QPushButton(rectangleSelection)
        self.updateButton.setObjectName("updateButton")
        self.gridLayout_2.addWidget(self.updateButton, 4, 1, 1, 1)
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.label = QtWidgets.QLabel(rectangleSelection)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 1, 0, 1, 3, QtCore.Qt.AlignHCenter)
        self.formLayout = QtWidgets.QFormLayout()
        self.formLayout.setObjectName("formLayout")
        self.topLeftXLabel = QtWidgets.QLabel(rectangleSelection)
        self.topLeftXLabel.setObjectName("topLeftXLabel")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.topLeftXLabel)
        self.topLeftXLineEdit = QtWidgets.QLineEdit(rectangleSelection)
        self.topLeftXLineEdit.setEnabled(True)
        self.topLeftXLineEdit.setMaximumSize(QtCore.QSize(60, 16777215))
        self.topLeftXLineEdit.setReadOnly(True)
        self.topLeftXLineEdit.setObjectName("topLeftXLineEdit")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.topLeftXLineEdit)
        self.bottomLeftXLabel = QtWidgets.QLabel(rectangleSelection)
        self.bottomLeftXLabel.setObjectName("bottomLeftXLabel")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.bottomLeftXLabel)
        self.bottomLeftXLineEdit = QtWidgets.QLineEdit(rectangleSelection)
        self.bottomLeftXLineEdit.setEnabled(True)
        self.bottomLeftXLineEdit.setMaximumSize(QtCore.QSize(60, 16777215))
        self.bottomLeftXLineEdit.setReadOnly(True)
        self.bottomLeftXLineEdit.setObjectName("bottomLeftXLineEdit")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.bottomLeftXLineEdit)
        self.topRightXLabel = QtWidgets.QLabel(rectangleSelection)
        self.topRightXLabel.setObjectName("topRightXLabel")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.topRightXLabel)
        self.topRightXLineEdit = QtWidgets.QLineEdit(rectangleSelection)
        self.topRightXLineEdit.setEnabled(True)
        self.topRightXLineEdit.setMaximumSize(QtCore.QSize(60, 16777215))
        self.topRightXLineEdit.setReadOnly(True)
        self.topRightXLineEdit.setObjectName("topRightXLineEdit")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.topRightXLineEdit)
        self.bottomRightXLabel = QtWidgets.QLabel(rectangleSelection)
        self.bottomRightXLabel.setObjectName("bottomRightXLabel")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.bottomRightXLabel)
        self.bottomRightXLineEdit = QtWidgets.QLineEdit(rectangleSelection)
        self.bottomRightXLineEdit.setEnabled(True)
        self.bottomRightXLineEdit.setMaximumSize(QtCore.QSize(60, 16777215))
        self.bottomRightXLineEdit.setReadOnly(True)
        self.bottomRightXLineEdit.setObjectName("bottomRightXLineEdit")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.bottomRightXLineEdit)
        self.gridLayout.addLayout(self.formLayout, 8, 0, 1, 1)
        self.formLayout_2 = QtWidgets.QFormLayout()
        self.formLayout_2.setSizeConstraint(QtWidgets.QLayout.SetFixedSize)
        self.formLayout_2.setObjectName("formLayout_2")
        self.topLeftYLabel = QtWidgets.QLabel(rectangleSelection)
        self.topLeftYLabel.setObjectName("topLeftYLabel")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.topLeftYLabel)
        self.topLeftYLineEdit = QtWidgets.QLineEdit(rectangleSelection)
        self.topLeftYLineEdit.setEnabled(True)
        self.topLeftYLineEdit.setMaximumSize(QtCore.QSize(60, 16777215))
        self.topLeftYLineEdit.setReadOnly(True)
        self.topLeftYLineEdit.setObjectName("topLeftYLineEdit")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.topLeftYLineEdit)
        self.bottomLeftYLabel = QtWidgets.QLabel(rectangleSelection)
        self.bottomLeftYLabel.setObjectName("bottomLeftYLabel")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.bottomLeftYLabel)
        self.bottomLeftYLineEdit = QtWidgets.QLineEdit(rectangleSelection)
        self.bottomLeftYLineEdit.setEnabled(True)
        self.bottomLeftYLineEdit.setMaximumSize(QtCore.QSize(60, 16777215))
        self.bottomLeftYLineEdit.setReadOnly(True)
        self.bottomLeftYLineEdit.setObjectName("bottomLeftYLineEdit")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.bottomLeftYLineEdit)
        self.topRightYLabel = QtWidgets.QLabel(rectangleSelection)
        self.topRightYLabel.setObjectName("topRightYLabel")
        self.formLayout_2.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.topRightYLabel)
        self.topRightYLineEdit = QtWidgets.QLineEdit(rectangleSelection)
        self.topRightYLineEdit.setEnabled(True)
        self.topRightYLineEdit.setMaximumSize(QtCore.QSize(60, 16777215))
        self.topRightYLineEdit.setReadOnly(True)
        self.topRightYLineEdit.setObjectName("topRightYLineEdit")
        self.formLayout_2.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.topRightYLineEdit)
        self.bottomRightYLabel = QtWidgets.QLabel(rectangleSelection)
        self.bottomRightYLabel.setObjectName("bottomRightYLabel")
        self.formLayout_2.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.bottomRightYLabel)
        self.bottomRightYLineEdit = QtWidgets.QLineEdit(rectangleSelection)
        self.bottomRightYLineEdit.setEnabled(True)
        self.bottomRightYLineEdit.setMaximumSize(QtCore.QSize(60, 16777215))
        self.bottomRightYLineEdit.setReadOnly(True)
        self.bottomRightYLineEdit.setObjectName("bottomRightYLineEdit")
        self.formLayout_2.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.bottomRightYLineEdit)
        self.gridLayout.addLayout(self.formLayout_2, 8, 1, 1, 1)
        self.rectangleSelectionComboBox = QtWidgets.QComboBox(rectangleSelection)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.rectangleSelectionComboBox.sizePolicy().hasHeightForWidth())
        self.rectangleSelectionComboBox.setSizePolicy(sizePolicy)
        self.rectangleSelectionComboBox.setMinimumSize(QtCore.QSize(200, 0))
        self.rectangleSelectionComboBox.setMaxVisibleItems(30)
        self.rectangleSelectionComboBox.setSizeAdjustPolicy(QtWidgets.QComboBox.AdjustToContents)
        self.rectangleSelectionComboBox.setObjectName("rectangleSelectionComboBox")
        self.rectangleSelectionComboBox.addItem("")
        self.rectangleSelectionComboBox.addItem("")
        self.rectangleSelectionComboBox.addItem("")
        self.gridLayout.addWidget(self.rectangleSelectionComboBox, 2, 0, 1, 3, QtCore.Qt.AlignHCenter)
        self.gridLayout_2.addLayout(self.gridLayout, 2, 1, 1, 1)

        self.retranslateUi(rectangleSelection)
        QtCore.QMetaObject.connectSlotsByName(rectangleSelection)

    def retranslateUi(self, rectangleSelection):
        _translate = QtCore.QCoreApplication.translate
        rectangleSelection.setWindowTitle(_translate("rectangleSelection", "rectangleSelection"))
        self.updateButton.setText(_translate("rectangleSelection", "Create or update Rectangle"))
        self.label.setText(_translate("rectangleSelection", "Rectangle selection coordinates"))
        self.topLeftXLabel.setText(_translate("rectangleSelection", "Top Left X"))
        self.bottomLeftXLabel.setText(_translate("rectangleSelection", "Bottom Left X"))
        self.topRightXLabel.setText(_translate("rectangleSelection", "Top Right X"))
        self.bottomRightXLabel.setText(_translate("rectangleSelection", "Bottom Right X"))
        self.topLeftYLabel.setText(_translate("rectangleSelection", "Top Left Y"))
        self.bottomLeftYLabel.setText(_translate("rectangleSelection", "Bottom Left Y"))
        self.topRightYLabel.setText(_translate("rectangleSelection", "Top Right Y"))
        self.bottomRightYLabel.setText(_translate("rectangleSelection", "Bottom Right Y"))
        self.rectangleSelectionComboBox.setCurrentText(_translate("rectangleSelection", "Select rectangle creation "))
        self.rectangleSelectionComboBox.setItemText(0, _translate("rectangleSelection", "Select rectangle creation "))
        self.rectangleSelectionComboBox.setItemText(1, _translate("rectangleSelection", "Left top and Right bottom"))
        self.rectangleSelectionComboBox.setItemText(2, _translate("rectangleSelection", "Left bottom and Right top"))

