
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'BOOLEAN COLON COMMA COMMENT DEDENT INDENT NUMBER STRINGblocks : blockblocks : blocks blockblock : title members DEDENTblock : pairblock : commenttitle : STRING COLON INDENT\n             | list COLON INDENTlist : STRING COMMA STRING\n            | list COMMA STRINGmembers : pairmembers : pair membersmembers : title members DEDENTmembers : title members DEDENT memberspair : STRING STRINGpair : STRING COLON STRINGpair : STRING NUMBERpair : STRING COLON NUMBERpair : STRING BOOLEANpair : STRING COLON BOOLEANcomment : COMMENT'
    
_lr_action_items = {'STRING':([0,1,2,3,4,5,6,8,9,10,12,13,14,15,16,17,18,20,22,24,25,26,27,28,30,32,],[6,6,-1,13,-4,-5,14,-20,-2,13,13,14,-14,25,-16,-18,29,31,-3,25,-15,-6,-17,-19,-7,13,]),'COMMENT':([0,1,2,4,5,8,9,14,16,17,22,25,27,28,],[8,8,-1,-4,-5,-20,-2,-14,-16,-18,-3,-15,-17,-19,]),'$end':([1,2,4,5,8,9,14,16,17,22,25,27,28,],[0,-1,-4,-5,-20,-2,-14,-16,-18,-3,-15,-17,-19,]),'COLON':([6,7,13,29,31,],[15,19,24,-8,-9,]),'NUMBER':([6,13,15,24,],[16,16,27,27,]),'BOOLEAN':([6,13,15,24,],[17,17,28,28,]),'COMMA':([6,7,13,29,31,],[18,20,18,-8,-9,]),'DEDENT':([11,12,14,16,17,21,23,25,27,28,32,33,],[22,-10,-14,-16,-18,32,-11,-15,-17,-19,-12,-13,]),'INDENT':([15,19,24,],[26,30,26,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'blocks':([0,],[1,]),'block':([0,1,],[2,9,]),'title':([0,1,3,10,12,32,],[3,3,10,10,10,10,]),'pair':([0,1,3,10,12,32,],[4,4,12,12,12,12,]),'comment':([0,1,],[5,5,]),'list':([0,1,3,10,12,32,],[7,7,7,7,7,7,]),'members':([3,10,12,32,],[11,21,23,33,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> blocks","S'",1,None,None,None),
  ('blocks -> block','blocks',1,'p_blocks_single','parser.py',21),
  ('blocks -> blocks block','blocks',2,'p_blocks','parser.py',30),
  ('block -> title members DEDENT','block',3,'p_block_title','parser.py',41),
  ('block -> pair','block',1,'p_block_pair','parser.py',48),
  ('block -> comment','block',1,'p_block_comment','parser.py',53),
  ('title -> STRING COLON INDENT','title',3,'p_title','parser.py',58),
  ('title -> list COLON INDENT','title',3,'p_title','parser.py',59),
  ('list -> STRING COMMA STRING','list',3,'p_list','parser.py',64),
  ('list -> list COMMA STRING','list',3,'p_list','parser.py',65),
  ('members -> pair','members',1,'p_members','parser.py',70),
  ('members -> pair members','members',2,'p_members_multiple_pairs','parser.py',75),
  ('members -> title members DEDENT','members',3,'p_members_nested_title','parser.py',80),
  ('members -> title members DEDENT members','members',4,'p_members_nested_title_memb','parser.py',85),
  ('pair -> STRING STRING','pair',2,'p_pair','parser.py',90),
  ('pair -> STRING COLON STRING','pair',3,'p_pair_colon','parser.py',95),
  ('pair -> STRING NUMBER','pair',2,'p_pair_number','parser.py',100),
  ('pair -> STRING COLON NUMBER','pair',3,'p_pair_colon_number','parser.py',105),
  ('pair -> STRING BOOLEAN','pair',2,'p_pair_boolean','parser.py',110),
  ('pair -> STRING COLON BOOLEAN','pair',3,'p_pair_colon_boolean','parser.py',115),
  ('comment -> COMMENT','comment',1,'p_comment','parser.py',122),
]
