# Generated by Django 2.2.1 on 2021-02-08 06:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import functools
import lavender.texture
import nidhoggr.core.texture


class Migration(migrations.Migration):

    dependencies = [
        ('lavender', '0009_force_non_null_token_uuid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='wardrobe',
            old_name='cloak_height',
            new_name='cape_height',
        ),
        migrations.RenameField(
            model_name='wardrobe',
            old_name='cloak_width',
            new_name='cape_width',
        ),
        migrations.RemoveField(
            model_name='wardrobe',
            name='cloak',
        ),
        migrations.AddField(
            model_name='wardrobe',
            name='cape',
            field=models.ImageField(blank=True, height_field='cape_height', null=True, upload_to=functools.partial(lavender.texture.path_handler, *(nidhoggr.core.texture.TextureType('CAPE'),), **{}), width_field='cape_width'),
        ),
        migrations.AlterField(
            model_name='wardrobe',
            name='player',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
