
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

from __future__ import absolute_import
import json

version_json = '''
{
 "date": "2021-02-05T18:49:29+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "3fa2a00f1e7ddca5e38e607d7a99958ddbdd9edd",
 "version": "v0.20.2"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
