from enum import Enum


class ClickPosition(Enum):
    CENTER = "CENTER"
    LEFT_UPPER_CORNER = "LEFT_UPPER_CORNER"
    LEFT_LOWER_CORNER = "LEFT_LOWER_CORNER"
    RIGHT_UPPER_CORNER = "RIGHT_UPPER_CORNER"
    RIGHT_LOWER_CORNER = "RIGHT_LOWER_CORNER"
