from enum import Enum


class RowType(Enum):
    TEST_START_TIME = "TEST_START_TIME"
    TEST_END_TIME = "TEST_END_TIME"
    TEST_STATUS = "TEST_STATUS"
    TEST_DETAILS = "TEST_DETAILS"
    ACTION = "ACTION"
    INTERNAL_ACTION = "INTERNAL_ACTION"
    LOGS = "LOGS"
    USER_LOGS = "USER_LOGS"
    TEST_ACTION = "TEST_ACTION"
    BROWSER_CONSOLE = "BROWSER_CONSOLE"
    BROWSER_XHR_REQUEST = "BROWSER_XHR_REQUEST"
    BROWSER_NETWORK = "BROWSER_NETWORK"
    HTML = "HTML"
    DEBUG = "DEBUG"
