
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-02-10T05:08:06+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "e7c495beff64dc9fe21b7981092d89a6f7dcb927",
 "version": "1.14.6.post.dev91"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
