# -*- coding: utf-8 -*-
from setuptools import setup

packages = \
['aleksis',
 'aleksis.core',
 'aleksis.core.migrations',
 'aleksis.core.templatetags',
 'aleksis.core.tests.browser',
 'aleksis.core.tests.models',
 'aleksis.core.tests.templatetags',
 'aleksis.core.tests.util',
 'aleksis.core.tests.views',
 'aleksis.core.util']

package_data = \
{'': ['*'],
 'aleksis.core': ['locale/ar/LC_MESSAGES/django.po',
                  'locale/ar/LC_MESSAGES/django.po',
                  'locale/ar/LC_MESSAGES/djangojs.po',
                  'locale/ar/LC_MESSAGES/djangojs.po',
                  'locale/de_DE/LC_MESSAGES/django.po',
                  'locale/de_DE/LC_MESSAGES/django.po',
                  'locale/de_DE/LC_MESSAGES/djangojs.po',
                  'locale/de_DE/LC_MESSAGES/djangojs.po',
                  'locale/fr/LC_MESSAGES/django.po',
                  'locale/fr/LC_MESSAGES/django.po',
                  'locale/fr/LC_MESSAGES/djangojs.po',
                  'locale/fr/LC_MESSAGES/djangojs.po',
                  'locale/la/LC_MESSAGES/django.po',
                  'locale/la/LC_MESSAGES/django.po',
                  'locale/la/LC_MESSAGES/djangojs.po',
                  'locale/la/LC_MESSAGES/djangojs.po',
                  'locale/nb_NO/LC_MESSAGES/django.po',
                  'locale/nb_NO/LC_MESSAGES/django.po',
                  'locale/nb_NO/LC_MESSAGES/djangojs.po',
                  'locale/nb_NO/LC_MESSAGES/djangojs.po',
                  'locale/tr_TR/LC_MESSAGES/django.po',
                  'locale/tr_TR/LC_MESSAGES/django.po',
                  'locale/tr_TR/LC_MESSAGES/djangojs.po',
                  'locale/tr_TR/LC_MESSAGES/djangojs.po',
                  'static/*',
                  'static/icons/*',
                  'static/img/*',
                  'static/js/*',
                  'templates/*',
                  'templates/components/*',
                  'templates/core/*',
                  'templates/core/additional_field/*',
                  'templates/core/announcement/*',
                  'templates/core/dashboard_widget/*',
                  'templates/core/data_check/*',
                  'templates/core/group/*',
                  'templates/core/group_type/*',
                  'templates/core/management/*',
                  'templates/core/pages/*',
                  'templates/core/partials/*',
                  'templates/core/person/*',
                  'templates/core/school_term/*',
                  'templates/django_tables2/*',
                  'templates/dynamic_preferences/*',
                  'templates/impersonate/*',
                  'templates/material/*',
                  'templates/material/fields/*',
                  'templates/search/*',
                  'templates/search/indexes/core/*',
                  'templates/sms/*',
                  'templates/templated_email/*',
                  'templates/two_factor/*',
                  'templates/two_factor/core/*',
                  'templates/two_factor/profile/*']}

install_requires = \
['Django>=3.0,<4.0',
 'Pillow>=8.0,<9.0',
 'bs4>=0.0.1,<0.0.2',
 'calendarweek>=0.4.3,<0.5.0',
 'celery-progress>=0.0.14,<0.0.15',
 'colour>=0.1.5,<0.2.0',
 'django-any-js>=1.0,<2.0',
 'django-bleach>=0.6.1,<0.7.0',
 'django-cachalot>=2.3.2,<3.0.0',
 'django-cache-memoize>=0.1.6,<0.2.0',
 'django-ckeditor>=6.0.0,<7.0.0',
 'django-colorfield>=0.3.0,<0.4.0',
 'django-dbbackup>=3.3.0,<4.0.0',
 'django-debug-toolbar>=2.0,<3.0',
 'django-dirtyfields>=1.5.0,<2.0.0',
 'django-dynamic-preferences>=1.9,<2.0',
 'django-extensions>=3.1.1,<4.0.0',
 'django-favicon-plus-reloaded>=1.0.4,<2.0.0',
 'django-filter>=2.2.0,<3.0.0',
 'django-guardian>=2.2.0,<3.0.0',
 'django-hattori>=0.2,<0.3',
 'django-haystack==3.0b1',
 'django-health-check>=3.12.1,<4.0.0',
 'django-impersonate>=1.4,<2.0',
 'django-ipware>=3.0,<4.0',
 'django-js-reverse>=0.9.1,<0.10.0',
 'django-jsonstore>=0.5.0,<0.6.0',
 'django-maintenance-mode>=0.15.0,<0.16.0',
 'django-material>=1.6.0,<2.0.0',
 'django-menu-generator-ng>=1.2.0,<2.0.0',
 'django-middleware-global-request>=0.1.2,<0.2.0',
 'django-model-utils>=4.0.0,<5.0.0',
 'django-phonenumber-field[phonenumbers]<5.1',
 'django-polymorphic>=3.0.0,<4.0.0',
 'django-prometheus>=2.1.0,<3.0.0',
 'django-pwa>=1.0.8,<2.0.0',
 'django-reversion>=3.0.7,<4.0.0',
 'django-sass-processor>=0.8,<0.9',
 'django-settings-context-processor>=0.2,<0.3',
 'django-tables2>=2.1,<3.0',
 'django-templated-email>=2.3.0,<3.0.0',
 'django-two-factor-auth[phonenumbers,yubikey,sms,call]>=1.12.1,<2.0.0',
 'django-yarnpkg>=6.0,<7.0',
 'django_select2>=7.1,<8.0',
 'django_widget_tweaks>=1.4.5,<2.0.0',
 'dynaconf[toml,ini,yaml]>=3.1,<4.0',
 'html2text>=2020.0.0,<2021.0.0',
 'ipython>=7.20.0,<8.0.0',
 'libsass>=0.20.0,<0.21.0',
 'license-expression>=1.2,<2.0',
 'psutil>=5.7.0,<6.0.0',
 'psycopg2>=2.8,<3.0',
 'python-memcached>=1.59,<2.0',
 'requests>=2.22,<3.0',
 'rules>=2.2,<3.0',
 'spdx-license-list>=0.5.0,<0.6.0']

extras_require = \
{':python_version < "3.9"': ['importlib-metadata>=3.0.0,<4.0.0'],
 'celery': ['Celery[redis,django]>=5.0.0,<6.0.0',
            'django-celery-results>=2.0.0,<3.0.0',
            'django-celery-beat>=2.0.0,<3.0.0',
            'django-celery-email>=3.0.0,<4.0.0',
            'celery-haystack-ng>=0.20,<0.21'],
 'ldap': ['django-auth-ldap>=2.2,<3.0']}

entry_points = \
{'console_scripts': ['aleksis-admin = aleksis.core.__main__:aleksis_cmd']}

setup_kwargs = {
    'name': 'aleksis-core',
    'version': '2.0a4',
    'description': 'AlekSIS (School Information System)\u200a—\u200aCore',
    'long_description': 'AlekSIS (School Information System)\u200a—\u200aCore (Core functionality and app framework)\n=================================================================================\n\nAlekSIS standard distribution\n-----------------------------\n\nThe AlekSIS standard distribution with information about all official apps\ncan be found on `EduGit`_.\n\nFeatures\n--------\n\nThe AlekSIS-Core currently provides the following features:\n\n* For users:\n\n * Custom menu entries (e.g. in footer)\n * Global preferences\n * Group types\n * Manage announcements\n * Manage groups\n * Manage persons\n * Notifications via SMS email or dashboard\n * Rules and permissions for users, objects and pages\n * Two factor authentication via Yubikey, OTP or SMS\n * User preferences\n\n* For admins\n\n * Asynchronous tasks with celery\n * Authentication via LDAP\n * Automatic backup of database, static and media files\n\nLicence\n-------\n\n::\n\n  Copyright © 2017, 2018, 2019, 2020 Jonathan Weth <wethjo@katharineum.de>\n  Copyright © 2017, 2018, 2019 Frank Poetzsch-Heffter <p-h@katharineum.de>\n  Copyright © 2018, 2019, 2020 Julian Leucker <leuckeju@katharineum.de>\n  Copyright © 2018, 2019, 2020 Hangzhi Yu <yuha@katharineum.de>\n  Copyright © 2019, 2020 Dominik George <dominik.george@teckids.org>\n  Copyright © 2019, 2020 Tom Teichler <tom.teichler@teckids.org>\n  Copyright © 2019 mirabilos <thorsten.glaser@teckids.org>\n\n  Licenced under the EUPL, version 1.2 or later\n\nPlease see the LICENCE.rst file accompanying this distribution for the\nfull licence text or on the `European Union Public Licence`_ website\nhttps://joinup.ec.europa.eu/collection/eupl/guidelines-users-and-developers\n(including all other official language versions).\n\n.. _AlekSIS: https://edugit.org/AlekSIS/Official/AlekSIS\n.. _European Union Public Licence: https://eupl.eu/\n.. _EduGit: https://edugit.org/AlekSIS/official/AlekSIS\n',
    'author': 'Dominik George',
    'author_email': 'dominik.george@teckids.org',
    'maintainer': 'Jonathan Weth',
    'maintainer_email': 'wethjo@katharineum.de',
    'url': 'https://aleksis.org/',
    'packages': packages,
    'package_data': package_data,
    'install_requires': install_requires,
    'extras_require': extras_require,
    'entry_points': entry_points,
    'python_requires': '>=3.7,<4.0',
}


setup(**setup_kwargs)
