
# This file was generated by 'versioneer.py' (0.15) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json
import sys

version_json = '''
{
 "dirty": false,
 "error": null,
 "full-revisionid": "42c89901e80d97bf8e10862107a55601a07cf48d",
 "version": "2403"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
