# coding: utf-8

"""
    Aliro Quantum App

    This is an api for the Aliro Quantum App  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Contact: nick@aliroquantum.com
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest
import datetime

import aliro_quantum
from aliro_quantum.models.api_key_response import ApiKeyResponse  # noqa: E501
from aliro_quantum.rest import ApiException

class TestApiKeyResponse(unittest.TestCase):
    """ApiKeyResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional):
        """Test ApiKeyResponse
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # model = aliro_quantum.models.api_key_response.ApiKeyResponse()  # noqa: E501
        if include_optional :
            return ApiKeyResponse(
                data = aliro_quantum.models.api_key.ApiKey(
                    api_key = '0', )
            )
        else :
            return ApiKeyResponse(
        )

    def testApiKeyResponse(self):
        """Test ApiKeyResponse"""
        inst_req_only = self.make_instance(include_optional=False)
        inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == '__main__':
    unittest.main()
