# coding: utf-8

"""
    Aliro Quantum App

    This is an api for the Aliro Quantum App  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Contact: nick@aliroquantum.com
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import aliro_quantum
from aliro_quantum.api.credentials_api import CredentialsApi  # noqa: E501
from aliro_quantum.rest import ApiException


class TestCredentialsApi(unittest.TestCase):
    """CredentialsApi unit test stubs"""

    def setUp(self):
        self.api = aliro_quantum.api.credentials_api.CredentialsApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_credentials_vendor_delete(self):
        """Test case for credentials_vendor_delete

        delete vendor credentials for a user  # noqa: E501
        """
        pass

    def test_credentials_vendor_put(self):
        """Test case for credentials_vendor_put

        add vendor credentials for a user  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
