# Generated by Django 2.2.8 on 2019-12-17 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_eveonline_doctrine_manager', '0002_evefitting_ship_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evefitting',
            name='ship_id',
            field=models.IntegerField(blank=True, editable=False, null=True),
        ),
    ]
