# Generated by Django 2.2.13 on 2020-10-09 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_eveonline_doctrine_manager', '0006_eveskillplan_skills'),
    ]

    operations = [
        migrations.AddField(
            model_name='evedoctrinerole',
            name='color',
            field=models.CharField(choices=[('primary', 'Blue'), ('secondary', 'Gray'), ('success', 'Green'), ('danger', 'Red'), ('warning', 'Yellow'), ('info', 'Light Blue'), ('dark', 'Dark Gray')], default='primary', max_length=32),
            preserve_default=False,
        ),
    ]
