# Generated by Django 2.2.13 on 2020-10-16 19:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('django_eveonline_connector', '0036_auto_20201004_0148'),
        ('django_eveonline_doctrine_manager', '0009_evecharacterreport'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='EveCharacterReport',
            new_name='EveCharacterDoctrineReport',
        ),
    ]
