# Generated by Django 2.2.13 on 2020-10-19 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_eveonline_doctrine_manager', '0011_auto_20201019_1314'),
    ]

    operations = [
        migrations.AddField(
            model_name='evedoctrinesettings',
            name='seeding_contract_prefix',
            field=models.CharField(blank=True, default=None, max_length=12, null=True),
        ),
    ]
