# Generated by Django 2.2.13 on 2020-10-25 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_eveonline_doctrine_manager', '0012_evedoctrinesettings_seeding_contract_prefix'),
    ]

    operations = [
        migrations.AddField(
            model_name='evefitting',
            name='market_format_raw',
            field=models.TextField(default='{}'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='evefitting',
            name='parsed_format_raw',
            field=models.TextField(default='{}'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='evefitting',
            name='required_skills_raw',
            field=models.TextField(default='{}'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='evefitting',
            name='ship_name',
            field=models.CharField(default='Unknown Hull', max_length=128),
        ),
    ]
