# Generated by Django 2.2.13 on 2020-10-26 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_eveonline_doctrine_manager', '0014_auto_20201025_1838'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evefitting',
            name='market_format_raw',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='evefitting',
            name='parsed_format_raw',
            field=models.TextField(blank=True, null=True),
        ),
    ]
